#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      1.0
yabai -m config normal_window_opacity        0.85
yabai -m config window_border                on
yabai -m config active_window_border_color   0xE02d74da
yabai -m config normal_window_border_color   0x4444444444444
yabai -m config insert_feedback_color        
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10

float_regex="(VLC|Friendly Streaming|Cisco AnyConnect Secure Mobility Client)"
yabai -m rule --add app="${float_regex}" manage=off border=off
yabai -m rule --add app="(Slack|Google Chat)" space=4

